### ISSUE TITLE
Friends/Groups

### ISSUE THREAD

**Issue by joelddick** [sraje/CAPSTONE#28]

**Comment by chriskarcher** [comment]
Hey I'm doing this

**Comment by chriskarcher** [comment]
https://parse.com/tutorials/anypic#model
https://parse.com/tutorials/anypic#follow

These look helpful.

**Comment by chriskarcher** [comment]
ck/friends_and_share

Added ability to add friends. Displaying friends in accordion menu. Accessing parse to check if users are exist tends to delete the bike list, so I removed it for now.
